USE codeup_test_db;
DROP TABLE IF EXISTS albums;

CREATE TABLE albums (

	id INT UNSIGNED NOT NULL AUTO_INCREMENT, 
	artist_name VARCHAR(80) NOT NULL,
	release_date YEAR(4) NOT NULL,
	sales FLOAT(10,2) UNSIGNED NOT NULL, 
	genre VARCHAR(20) NOT NULL,
	PRIMARY KEY (id)

);
